name: 'Elastic Vale Linter - Report'
description: 'Post Vale results as PR comment (Step 2: Reporting)'
author: 'Elastic'

branding:
  icon: 'message-circle'
  color: 'blue'

inputs:
  github_token:
    default: ${{ github.token }}
    type: string
    description: 'GitHub token for posting PR comments'
    required: false
  download_artifacts:
    description: 'Whether to download Vale results from artifacts from the linting workflow'
    type: boolean
    default: true
    required: false

runs:
  using: 'composite'
  steps:
    - name: Download Vale results
      if: inputs.download_artifacts == 'true'
      uses: dawidd6/action-download-artifact@5c98f0b039f36ef966fdb7dfa9779262785ecb05 # v14
      with:
        name: vale-results
        github_token: ${{ inputs.github_token }}
        workflow: lint.yml
        run_id: ${{ github.event.workflow_run.id }}
    
    - name: Check if results exist
      id: check-results
      shell: bash
      run: |
        if [ -f vale_report.md ]; then
          echo "has_results=true" >> $GITHUB_OUTPUT
          echo "✓ Vale results found"
        else
          echo "has_results=false" >> $GITHUB_OUTPUT
          echo "⚠️ No Vale results found"
        fi
    
    - name: Get PR number
      id: pr-number
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        # Extract PR number from the workflow_run event
        # First try the pull_requests array
        PR_NUMBER=$(echo '${{ toJSON(github.event.workflow_run.pull_requests) }}' | jq -r '.[0].number')
        
        # If that's null, search for PR by head SHA (works for forks)
        if [ "$PR_NUMBER" == "null" ] || [ -z "$PR_NUMBER" ]; then
          echo "Pull requests array is empty, searching by head SHA..."
          PR_NUMBER=$(gh pr list --repo ${{ github.repository }} --state open --json number,headRefOid \
            --jq '.[] | select(.headRefOid == "${{ github.event.workflow_run.head_sha }}") | .number' | head -1)
        fi
        
        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        echo "PR number: $PR_NUMBER"
    
    - name: Post sticky comment
      if: steps.check-results.outputs.has_results == 'true' && steps.pr-number.outputs.pr_number != 'null'
      uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
      with:
        header: elastic-vale-results
        path: vale_report.md
        number: ${{ steps.pr-number.outputs.pr_number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
    
    - name: Cleanup artifacts
      if: always()
      shell: bash
      run: |
        rm -f vale_report.md
        rm -f issue_counts.txt
        echo "✓ Cleanup complete"
